### ISSUE TITLE
Hostname for bastion

### ISSUE THREAD

**Issue by aarcro** [remind101/stacker_blueprints#108]
As a lazy admin
I want a predicable DNS name for my bastion box(s)
So that I have a reliable endpoint to connect to.

I'm not sure how to accomplish this, especially for users that choose to run more than one bastion. You'd likely have to add an ELB forwarding port 22, and deal with host keys.

**Comment by russellballestrini** [comment]
There is no need for an ELB. We solve this using the `route53` blueprint in this `stacker_blueprints` repo.

Here is an example where I take the `Output` from the `Bastion` blueprint and use it to create DNS `A` records:

```
  - name: route53-main-zone
    class_path: blueprints.route53.DNSRecords
    variables:
      HostedZoneName: ${basedomain}.
      Comment: ${basedomain} managed by stacker
      RecordSets:

        - Name: bastion.${basedomain}.
          Type: A
          TTL: 60
          ResourceRecords:
            - ${output bastion::PublicIp0}
        - Name: bastion0.${basedomain}.
          Type: A
          TTL: 60
          ResourceRecords:
            - ${output bastion::PublicIp0}
        - Name: bastion1.${basedomain}.
          Type: A
          TTL: 60
          ResourceRecords:
            - ${output bastion::PublicIp1}
```
